# Generated by Django 5.1.7 on 2025-03-08 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0006_alter_productmedia_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["code"]},
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "mp4",
                            "mov",
                            "zip",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="is_selected",
            field=models.BooleanField(default=True),
        ),
    ]
